name: Deploy Cognito Auth Stack

on:
  push:
    branches:
      - main
    paths:
      - 'infra/cognito-stack.yml'   # Only redeploy if infra changes

jobs:
  deploy-auth:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Deploy Cognito stack
        run: |
          echo "Deploying Cognito stack..."
          aws cloudformation deploy \
            --template-file infra/cognito-stack.yml \
            --stack-name discordclone-auth-dev \
            --capabilities CAPABILITY_NAMED_IAM \
            --region us-west-1 \
            --parameter-overrides Environment=dev FrontendDomain="" \
            --no-fail-on-empty-changeset
